name: Build VirtualSlate
on:
  push: {}
  pull_request: {}

jobs:
  Build-Extension:
    runs-on: ubuntu-latest
    steps:
      - name: Updates Packages
        run: apt-get update
      - name: Install Scons
        run: apt-get -y install scons gcc-mingw-w64
      - name: Install Compiler
        run: yes | apt-get install g++-mingw-w64-x86-64
      - name: Get Repo
        run: git clone --recurse-submodules https://github.com/James-Oswald/VirtualSlate.git
      - name: Arrive at Repo
        run: cd VirtualSlate
      - name: build Extension
        run: scons platform=windows
      - name: Upload Extension
        uses: actions/upload-artifact@v3
        with:
          name: VirtualSlateBuildFiles
          path: VirtualSlate
  Build-Game:
    runs-on: windows-latest
    steps:
      - name: Set Perms
      run: Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
      - name: Get Package Manager
      run: irm get.scoop.sh | iex
      - name: Download Godot
      run: scoop install godot
      - name: Retreive Build
      uses: actions/download-artifact@v3
      with:
        name: VirtualSlateBuildFiles
      - name: Change Directory
      run: cd VirtualSlate
      - name: Make Game
      run: godot --path project --headless --export-debug "Windows Desktop"
      - name: Get .exe
      uses: actions/upload-artifact@v3
      with:
        name: VirtualSlate-x64
        path: project/project.exe


