name: Build VirtualSlate
on:
  push: {}
  pull_request: {}
jobs:
  Build-Extension:
    runs-on: ubuntu-latest
    steps:
     - name: Updates Packages
       run: sudo apt-get update
     - name: Install Scons
       run: sudo apt-get -y install scons gcc-mingw-w64
     - name: Install Compiler
       run: yes | sudo apt-get install g++-mingw-w64-x86-64
     - name: Get Repo
       uses: actions/checkout@v4
       with:
         submodules: recursive
     - name: Build Extension
       run: scons platform=windows
     - name: Build
       id: build
       uses: manleydev/build-godot-action@v1.4.1
       with:
          name: VirtualSlate
          preset: win64
          debugMode: "false"
          projectDir: "VirtualSlate/project"
     - name: Upload Artifact
       uses: actions/upload-artifact@v3
       with:
          name: Client - win64
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}


