name: Build VirtualSlate
on:
  push: {}
  pull_request: {}
jobs:
  Build-Extension:
    runs-on: ubuntu-latest
    steps:
     - name: Updates Packages
       run: sudo apt-get update
     - name: Install Scons
       run: sudo apt-get -y install scons gcc-mingw-w64
     - name: Install Compiler
       run: yes | sudo apt-get install g++-mingw-w64-x86-64
     - name: Get Repo
       uses: actions/checkout@v4
       with:
         submodules: recursive
     - name: Build Extension
       run: scons platform=windows
     - name: Upload Artifact
       uses: actions/upload-artifact@v3
       with:
          name: VirtualSlateBuildFiles
          path: ./
  Build-Game:
    runs-on: windows-2019
    needs: Build-Extension
    steps:
      - name: Retreive Build
        uses: actions/download-artifact@v3
        with:
          name: VirtualSlateBuildFiles
      - name: Download Engine
        run: Invoke-WebRequest https://downloads.tuxfamily.org/godotengine/4.1.2/Godot_v4.1.2-stable_win64.exe.zip -OutFile godotbuilder.zip
      - name: Unizp Enginer
        run: Expand-Archive godotbuilder.zip -DestinationPath ./
      - name: Make Game
        run: ls; ./Godot_v4.1.2-stable_win64_console.exe --path project --export-debug "Windows Desktop"
      - name: Looking for game
        run: cd project; ls
      - name: Upload .exe
        uses: actions/upload-artifact@v3
        with:
          name: VirtualSlate-x64
          path: project/Project.exe

