name: Test VirtualSlate
on: 
  push: {}
jobs:
  LintCPP:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
      statuses: write
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: super-linter/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
