---
name: Test VirtualSlate
on: 
  push: { }
  pull_request: { }
jobs:
  LintCPP:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
      statuses: write
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: super-linter/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_CLANG_FORMAT: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  LintGDScript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.10
      - name: Install Dependencies
        run: python -m pip install --upgrade pip
      - name: Get Linter
        run: pip install "gdtoolkit==4.*"
      - name: Add linter to path
        run: echo "${HOME}/.local/bin" >> $GITHUB_PATH
      - name: Run Linter
        run: find project -name *.gd -exec gdlint {} \; 2>> gdErrors.txt 
      - name: Show Errors 
        run: cat gdErrors.txt
